name: icm
services:
    websites-staging:
        command: ["sleep", "infinity"]
        image: test
        container_name: icm-websites-staging
        restart: unless-stopped
        ports:
            - "5001:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        volumes:
            - ./ICM/ICM.WebSites/wwwroot/media:/app/wwwroot/media
            #- /var/icm/umbraco/staging/uSync:/app/uSync
            - /etc/icm/websites/keys:/etc/icm/websites/keys
        networks:
            - icm-websites-staging
networks:
    icm-websites-staging: